common:
    n_rows: 5000
    n_cols: 5000
    n_block_x: 25
    n_block_y: 20
    CM_OUTPUT_INTERVAL: 32
    SLOPE_SCALE: 10000
    ORDINALDAY_19710101: 719528
    probability_threshold: 0.99
    conse: 6
    band_num: 8
obcold:
    default_threshold: 15.086
    NAN_VAL: -9999
    NAN_VAL_UINT8: 255
    cm_scale: 100
    gate_thres: 7.289
    floodfill_thres: 0.5
    TOTAL_IMAGE_BANDS: 7
    total_landcover_category: 8
    min_category_samples: 600
    max_category_samples: 8000
    total_samples: 20000
    classification_year: 2001
    C1_threshold: 11.07
    C1_sizeslope: 0.1
    C2_threshold: 15.086
    C2_sizeslope: 0.05
    C3_threshold: 15.086
    C3_sizeslope: 0.05
    C4_threshold: 11.07
    C4_sizeslope: 0.1
    C5_threshold: 15.086
    C5_sizeslope: 0.05
    C6_threshold: 11.07
    C6_sizeslope: 0.1
    C7_threshold: 15.086
    C7_sizeslope: 0.05
    C8_threshold: 15.086
    C8_sizeslope: 0.05
    default_sizeslope: 0.1
    N_FEATURES: 3
stacking:
    QA_BITPACKED: True
    QA_CLEAR: 0
    QA_WATER: 1
    QA_SHADOW: 2
    QA_SNOW: 3
    QA_CLOUD: 4
    QA_FILL: 255
    QA_CIRRUS1: 7
    QA_CIRRUS2: 8
    QA_OCCLUSION: 9